# Generated by Django 3.1.6 on 2021-06-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPatient', models.TextField(default=None)),
                ('EIdnumber', models.CharField(default=None, max_length=20)),
                ('HPosition', models.TextField(default='')),
                ('Phealth', models.CharField(default=None, max_length=12)),
                ('companyp', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.TextField(default='')),
                ('CAddress', models.TextField(default='')),
                ('TNumber', models.CharField(default='', max_length=20)),
                ('Emailemp', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.CharField(choices=[('DENTAL', 'Dental Services'), ('APE', 'Annual Physical Examination'), ('OPCS', 'Out-Patient Care Services'), ('IPCS', 'In-Patient Care Services'), ('ECT', 'Emergency Care Treatment'), ('OTHERS', 'Additional Benefits')], default='', max_length=20)),
                ('Account', models.CharField(choices=[('NEW', 'New Account'), ('EXISTING', 'Existing Account ')], default='', max_length=20)),
                ('CNumber', models.CharField(default='', max_length=12)),
                ('companye', models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='MTList.companyemployee')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer', models.TextField(default='', max_length=12)),
                ('Allergies', models.TextField(default='', max_length=100)),
                ('MedicalConditions', models.TextField(default='')),
                ('CurrentMedications', models.TextField(default='')),
                ('DateRecord', models.TextField(default='', max_length=8)),
                ('ContactPerson', models.TextField(default='', max_length=30)),
                ('ContactNumber', models.CharField(default='', max_length=12)),
                ('RPerson', models.TextField(default='')),
                ('companye', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MTList.companyemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.TextField(default='', max_length=50)),
                ('DateApp', models.TextField(default='')),
                ('DoctorApp', models.TextField(default='')),
                ('companye', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MTList.companyemployee')),
                ('medicaloffers', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MTList.medicaloffers')),
            ],
        ),
    ]
