# Generated by Django 3.1.6 on 2021-06-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPatient', models.TextField(default=None, max_length=50)),
                ('EIdnumber', models.CharField(default=None, max_length=20)),
                ('Phealth', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.TextField(default='')),
                ('CAddress', models.TextField(default='')),
                ('Emailemp', models.CharField(default='', max_length=30)),
                ('TNumber', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNumber', models.CharField(default='', max_length=12)),
                ('DepartmentS', models.TextField(default='', max_length=80)),
                ('Services', models.CharField(choices=[('DENTAL', 'Dental Services'), ('APE', 'Annual Physical Examination'), ('OPCS', 'Out-Patient Care Services'), ('IPCS', 'In-Patient Care Services'), ('ECT', 'Emergency Care Treatment'), ('OTHERS', 'Additional Benefits')], default='', max_length=20)),
                ('Account', models.CharField(choices=[('NEW', 'New Account'), ('EXISTING', 'Existing Account ')], default='', max_length=20)),
                ('companye', models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='MTList.companyemployee')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergies', models.TextField(default='', max_length=100)),
                ('MedicalConditions', models.TextField(default='')),
                ('CurrentMedications', models.TextField(default='')),
                ('DateRecord', models.TextField(default='', max_length=8)),
                ('modality', models.TextField(default='', max_length=50)),
                ('ContactPerson', models.TextField(default='', max_length=30)),
                ('ContactNumber', models.CharField(default='', max_length=12)),
                ('RPerson', models.TextField(default='')),
                ('companye', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MTList.companyemployee')),
            ],
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='companyp',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='MTList.companyprofile'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOBirth', models.CharField(default='', max_length=8)),
                ('Emailemp', models.CharField(default='', max_length=50)),
                ('DName', models.TextField(default='', max_length=30)),
                ('Hospital', models.TextField(default='', max_length=50)),
                ('department', models.TextField(default='', max_length=30)),
                ('ServiceSS', models.TextField(default='', max_length=50)),
                ('ADate', models.TextField(default='', max_length=8)),
                ('companye', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MTList.companyemployee')),
            ],
        ),
    ]
